using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Identity;

namespace RealTime.API.Models
{
    public class Comment
    {
        public int Id { get; set; }

        [Required]
        public int DocumentId { get; set; }

        [Required]
        public string UserId { get; set; } = string.Empty;

        [Required]
        [MaxLength(1000)]
        public string Content { get; set; } = string.Empty;

        // The highlighted text that this comment is anchored to
        public string SelectionText { get; set; } = string.Empty;

        // Unique anchor ID generated by TipTap to map marks to comments
        [Required]
        public string CommentAnchorId { get; set; } = string.Empty;

        public int? ParentCommentId { get; set; }

        public DateTime? ResolvedAt { get; set; }

        public string? ResolvedById { get; set; }

        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

        // Navigation properties
        public Document? Document { get; set; }
        public IdentityUser? User { get; set; }
        public Comment? ParentComment { get; set; }
        public ICollection<Comment> Replies { get; set; } = new List<Comment>();
        public IdentityUser? ResolvedBy { get; set; }
    }
}
